plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dtdc.soprotest'
    compileSdk 35

    defaultConfig {
        applicationId "com.dtdc.soprotest"
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName "0.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
