plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dtdc.soprotest'
    compileSdk 35

    defaultConfig {
        applicationId "com.dtdc.soprotest"
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName "0.5.6"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
